name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Login to DockerHub and build/push Docker image
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build, tag, and push image to DockerHub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          IMAGE_NAME: my-image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:v2.0 .
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:v2.0

      # Deploy to EC2 instance
      - name: Deploy to EC2
        env:
          EC2_HOST: your-ec2-public-ip
          EC2_USERNAME: ec2-user
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          IMAGE_NAME: my-image
        run: |
          ssh -i $SSH_PRIVATE_KEY $EC2_USERNAME@$EC2_HOST "docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:v2.0 && docker stop my-container && docker rm my-container && docker run -d --name my-container -p 80:80 $DOCKERHUB_USERNAME/$IMAGE_NAME:v2.0"
